---
core:
  num_workers: 10
inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "../nuts/resources/inventory/hosts.yaml"
    group_file: "../nuts/resources/inventory/groups.yaml"
    defaults_file: "../nuts/resources/inventory/defaults.yaml"