test03:
  - PingRouter1FromRouter1
  - Ping
  - router01
  - 172.16.255.1
  - Success
  - connectivity

test04:
  - GetInterfacesFromRouter02
  - Show Interfaces
  - router02
  - No Target
  - {'GigabitEthernet1': True, 'GigabitEthernet2': True, 'GigabitEthernet3': True, 'GigabitEthernet4': True, 'Loopback0': True}
  - Show

test05:
  - TracerouteFromRouter1ToRouter3
  - Traceroute
  - router03
  - 172.16.14.4
  - ["172.16.13.1", "172.16.14.4"]
  - route

test06:
  - PingRouter1FromRouter2
  - Ping
  - router02
  - 172.16.255.1
  - Success
  - connectivity

test07:
  - PingRouter1FromRouter3
  - Ping
  - router03
  - 172.16.255.1
  - Success
  - connectivity

test08:
  - PingRouter1FromRouter4
  - Ping
  - router04
  - 172.16.255.1
  - Success
  - connectivity

test09:
  - PingRouter4FromRouter1
  - Ping
  - router01
  - 172.16.14.4
  - Success
  - connectivity

test10:
  - GetArpTableFromRouter1
  - Arp Table
  - router01
  - No Target
  - [
      {'interface': 'GigabitEthernet3', 'mac': '52:54:00:67:A5:39', 'ip': '172.16.12.1'},
      {'interface': 'GigabitEthernet3', 'mac': '52:54:00:28:F0:9D', 'ip': '172.16.12.2'},
      {'interface': 'GigabitEthernet4', 'mac': '52:54:00:16:91:60', 'ip': '172.16.13.1'},
      {'interface': 'GigabitEthernet4', 'mac': '52:54:00:12:E0:4C', 'ip': '172.16.13.3'},
      {'interface': 'GigabitEthernet2', 'mac': '52:54:00:63:CD:6C', 'ip': '172.16.14.1'},
      {'interface': 'GigabitEthernet2', 'mac': '52:54:00:5D:8E:C7', 'ip': '172.16.14.4'}
    ]
  - Arp

test11:
  - GetOspfNeighbors
  - Ospf Neighbor
  - router01
  - No Target
  - [
      {'Neighbor-ID': '172.16.255.3', 'Priority': '1', 'State': 'FULL/BDR', 'Address': '172.16.13.3', 'Interface': 'GigabitEthernet4'},
      {'Neighbor-ID': '172.16.255.2', 'Priority': '1', 'State': 'FULL/BDR', 'Address': '172.16.12.2', 'Interface': 'GigabitEthernet3'},
      {'Neighbor-ID': '172.16.255.4', 'Priority': '1', 'State': 'FULL/BDR', 'Address': '172.16.14.4', 'Interface': 'GigabitEthernet2'}
    ]
  - OSPF
