test01:
  - PingRouter1Loopback0
  - Ping
  - router01
  - 172.16.255.1
  - Success
  - connectivity

test02:
  - PingRouter1Loopback1
  - Ping
  - router01
  - 172.16.255.2
  - Success
  - connectivity

test03:
  - PingRouter1FromRouter1
  - Ping
  - router01
  - 172.16.255.1
  - Success
  - connectivity

test04:
  - GetInterfacesFromRouter02
  - Show Interfaces
  - router02
  - No Target
  - {'GigabitEthernet1': True, 'GigabitEthernet2': True, 'GigabitEthernet3': True, 'GigabitEthernet4': True, 'Loopback0': True}
  - Show

test06:
  - TracerouteFromRouter1ToRouter3
  - Traceroute
  - router03
  - 172.16.14.4
  - ["172.16.13.1", "172.16.14.4"]
  - route

test07:
  - PingRouter1FromRouter2
  - Ping
  - router02
  - 172.16.255.1
  - Success
  - connectivity

test08:
  - PingRouter1FromRouter3
  - Ping
  - router03
  - 172.16.255.1
  - Success
  - connectivity

test09:
  - PingRouter1FromRouter4
  - Ping
  - router04
  - 172.16.255.1
  - Success
  - connectivity

test10:
  - PingRouter4FromRouter1
  - Ping
  - router01
  - 172.16.14.4
  - Success
  - connectivity

test11:
  - PingRouter3FromRouter1
  - Ping
  - router01
  - 172.16.13.3
  - Success
  - connectivity

test12:
  - PingRouter2FromRouter1
  - Ping
  - router01
  - 172.16.255.2
  - Success
  - connectivity