test01:
  - PingRouter1Loopback0
  - Netmiko
  - router01
  - 172.16.255.1
  - Success rate is 100 percent (5/5)

test02:
  - PingRouter1Loopback1
  - Netmiko
  - router01
  - 172.16.255.2
  - Success rate is 100 percent (5/5)

test03:
  - PingSelf
  - Ping own ip-address
  - router01
  - 10.30.0.1
  - Success rate is 100 percent (5/5)

test04:
  - GetInterfacesFromRouter02
  - Show Interfaces
  - router02
  - Whatever
  - Whatever
